### ISSUE TITLE
Neopixel

### ISSUE THREAD

**Issue by Zeanon** [Armchair-Engineering/Archetype#6]
I'm considering options for a new toolhead and the Archetype breakneck ticks basically all boxes except for two:
Neopixel: I would love to have 2 neopixel to light the area around the nozzle and one as a status led(I mean the A in the fan shrouds basically screams LED to me)
Klicky NG: that would be cool as I have an unklicky NG already that is precise as hell but it's not that big of a deal as I can always print a normal unklicky

I would be happy to implement Neopixel support myself, but unfortunately I am not able to convert the Breakneck medium ducts to a step and AutoCAD is not able to open STLs.

**Comment by lraithel15133** [comment]
> I'm considering options for a new toolhead and the Archetype breakneck ticks basically all boxes except for two: Neopixel: I would love to have 2 neopixel to light the area around the nozzle and one as a status led(I mean the A in the fan shrouds basically screams LED to me) Klicky NG: that would be cool as I have an unklicky NG already that is precise as hell but it's not that big of a deal as I can always print a normal unklicky
> 
> I would be happy to implement Neopixel support myself, but unfortunately I am not able to convert the Breakneck medium ducts to a step and AutoCAD is not able to open STLs.

Step files are on our discord in the archetype channel. see pins. https://discord.gg/armchairengineeringsux
Will be uploaded to the repo when it is ready for more eyes.
