### ISSUE TITLE
Will the f3d file be updated? When? 

### ISSUE THREAD

**Issue by gengge** [Armchair-Engineering/Archetype#7]
STL modification is too troublesome.

**Comment by brianvoe** [comment]
I know everyone wants the CAD files but let them release it when they are ready.

**Comment by lraithel15133** [comment]
> STL modification is too troublesome.

On our discord, for now. https://discord.gg/armchairengineeringsux

**Comment by leddhedd** [comment]
i am currently in the process of a minor reworking of the internals, and a major CAD overhaul, once that is done, i will be releasing a newly updated CAD
